services:
  - type: web
    name: timbrobro-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ADMIN_TOKEN
        generateValue: true
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: SMTP_SERVER
        value: mail.gassstro.com
      - key: SMTP_PORT
        value: 587
      - key: ALLOWED_ORIGINS
        value: https://stefanonozza.github.io,http://localhost:8080
      - key: DOMAIN
        value: https://stefanonozza.github.io/timbrobro
      - key: DATABASE_URL
        fromDatabase:
          name: timbrobro-db
          property: connectionString

databases:
  - name: timbrobro-db
    databaseName: timbrobro
    plan: free
    region: frankfurt
